### ISSUE TITLE
Change "Add to cart" to symbol

### ISSUE THREAD

**Issue by BramWulteputte** [Blockstock-gg/blockstock-issues#28]
![184690055-5de75020-6785-4756-b07c-3c426b87b443](https://user-images.githubusercontent.com/66305419/187038729-63e196a2-4629-451a-8afd-0a50a5237ae9.png)
![184690093-d5f021d0-24a1-4a07-98cb-fd31008a74b2](https://user-images.githubusercontent.com/66305419/187038731-4c786b0a-1464-4d80-badc-275ab04fa4b8.png)

**Comment by DomasJar** [comment]
For future reference, we're using Google's material icons so you can find them easily here: 
https://fonts.google.com/icons?icon.query=cart&icon.set=Material+Icons
